// Node Sample Dockerfile - Multi-stage with Shell for Debugging
FROM node:12 AS stage1
ADD . /app
WORKDIR /app
RUN npm install
#Second Stage us
FROM gcr.io/distroless/nodejs:debug
COPY --from=stage1 /app /app
WORKDIR /app
EXPOSE 8080
CMD ["server.js"]
